// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.Service.AlgoTrades.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AlgoInstanceTradeResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AlgoInstanceTradeResponseModel
        /// class.
        /// </summary>
        public AlgoInstanceTradeResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AlgoInstanceTradeResponseModel
        /// class.
        /// </summary>
        public AlgoInstanceTradeResponseModel(string instanceId = default(string), bool? isBuy = default(bool?), double? price = default(double?), double? amount = default(double?), double? fee = default(double?), string orderId = default(string), string assetPair = default(string), string tradedAssetName = default(string), string walletId = default(string))
        {
            InstanceId = instanceId;
            IsBuy = isBuy;
            Price = price;
            Amount = amount;
            Fee = fee;
            OrderId = orderId;
            AssetPair = assetPair;
            TradedAssetName = tradedAssetName;
            WalletId = walletId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InstanceId")]
        public string InstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsBuy")]
        public bool? IsBuy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Fee")]
        public double? Fee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TradedAssetName")]
        public string TradedAssetName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletId")]
        public string WalletId { get; set; }

    }
}
